/*
  app.js — Main controller. Initializes the app and wires the modules together.
  Responsibility: hold UI state (current bookmarks, claimed deals), respond to
  user intent emitted by ui.js, and coordinate data.js (catalog), storage.js
  (Firestore), and auth.js (sign-in). This file contains no direct DOM,
  Firestore, or Firebase Auth calls — it delegates to the dedicated modules.
*/

(function defineAppController() {
  "use strict";

  /** Map of bookmarked business ids for the signed-in user, e.g. { id: true }. */
  var bookmarkedIds = {};

  /** Map of claimed-deal business ids for the signed-in user. */
  var claimedDealIds = {};

  /**
   * Count the keys in a map object.
   * @param {Object} map The map to count.
   * @returns {number} Number of own keys.
   */
  function countKeys(map) {
    return Object.keys(map).length;
  }

  /**
   * Re-run the current query and render the business grid.
   * @returns {void}
   */
  function refreshResults() {
    var values = currentQuery;
    var results = window.AppData.query(values);
    window.AppUI.renderBusinesses(results, bookmarkedIds);
  }

  /** The latest search/filter/sort values from the controls. */
  var currentQuery = { searchTerm: "", category: "all", sortBy: "featured" };

  /**
   * Refresh per-business review aggregates from Firestore so averages reflect
   * user-submitted reviews on top of seed ratings.
   * @returns {Promise<void>} Resolves once aggregates are applied.
   */
  function refreshReviewStats() {
    return window.AppStorage.getReviewStats().then(function (stats) {
      window.AppData.getAllBusinesses().forEach(function (business) {
        window.AppData.setReviewStats(business.id, stats[business.id] || { sum: 0, count: 0 });
      });
    });
  }

  /**
   * Update the favorites count badge from the current bookmark state.
   * @returns {void}
   */
  function updateFavoritesCount() {
    window.AppUI.updateFavoritesCount(countKeys(bookmarkedIds));
  }

  /**
   * Build the list of bookmarked business objects.
   * @returns {Array<Object>} The user's favorite businesses.
   */
  function getFavoriteBusinesses() {
    return Object.keys(bookmarkedIds)
      .map(function (id) {
        return window.AppData.getBusinessById(id);
      })
      .filter(function (business) {
        return business !== null;
      });
  }

  /**
   * Build a self-contained HTML report of the user's favorite businesses.
   * Used by both the export (download) and print actions.
   * @param {Array<Object>} favorites The favorite businesses.
   * @returns {string} A complete HTML document as a string.
   */
  function buildFavoritesReportHtml(favorites) {
    var user = window.AppAuth.getCurrentUser();
    var owner = user && user.displayName ? user.displayName : "Guest";
    var generated = new Date().toLocaleString("en-US");

    var rows = favorites
      .map(function (business) {
        var average = window.AppData.getAverageRating(business);
        var rating = average > 0 ? average.toFixed(1) + " / 5" : "No ratings yet";
        var deal = business.deal ? business.deal.title : "—";
        return (
          "<tr>" +
          "<td>" + escapeForReport(business.name) + "</td>" +
          "<td>" + escapeForReport(business.category) + "</td>" +
          "<td>" + escapeForReport(rating) + "</td>" +
          "<td>" + escapeForReport(business.address) + "</td>" +
          "<td>" + escapeForReport(business.phone) + "</td>" +
          "<td>" + escapeForReport(deal) + "</td>" +
          "</tr>"
        );
      })
      .join("");

    return (
      "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>" +
      "<title>My Favorite Local Businesses — Lake Forest, IL</title>" +
      "<style>" +
      "body{font-family:Arial,Helvetica,sans-serif;color:#1f2421;margin:40px;}" +
      "h1{font-size:22px;margin-bottom:4px;}" +
      "p.meta{color:#5d655e;margin-top:0;}" +
      "table{border-collapse:collapse;width:100%;margin-top:20px;}" +
      "th,td{border:1px solid #d0d4ce;padding:8px 10px;text-align:left;font-size:13px;}" +
      "th{background:#e6f0ea;}" +
      "footer{margin-top:24px;color:#8a918a;font-size:12px;}" +
      "</style></head><body>" +
      "<h1>My Favorite Local Businesses</h1>" +
      "<p class='meta'>Lake Forest, Illinois · Prepared for " + escapeForReport(owner) +
      " · " + escapeForReport(generated) + "</p>" +
      "<table><thead><tr>" +
      "<th>Business</th><th>Category</th><th>Rating</th><th>Address</th>" +
      "<th>Phone</th><th>Deal</th>" +
      "</tr></thead><tbody>" +
      rows +
      "</tbody></table>" +
      "<footer>Generated by Byte-Sized Business Boost · FBLA Coding &amp; Programming 2025–2026</footer>" +
      "</body></html>"
    );
  }

  /**
   * Escape text for safe inclusion in the generated report HTML.
   * @param {string} value Raw text.
   * @returns {string} HTML-escaped text.
   */
  function escapeForReport(value) {
    var text = value == null ? "" : String(value);
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  }

  /* ===================== Intent handlers (called by ui.js) ===================== */

  /**
   * Handle a change to the search/filter/sort controls.
   * @param {{searchTerm: string, category: string, sortBy: string}} values New values.
   * @returns {void}
   */
  function handleQueryChange(values) {
    currentQuery = values;
    refreshResults();
  }

  /**
   * Open the detail modal for a business, loading its reviews first.
   * @param {string} businessId The business to open.
   * @returns {void}
   */
  function handleOpenBusiness(businessId) {
    var business = window.AppData.getBusinessById(businessId);
    if (!business) {
      return;
    }

    /**
     * Open the detail modal with whatever reviews were available.
     * @param {Array<Object>} reviews The reviews to show (possibly empty).
     * @returns {void}
     */
    function showBusinessWithReviews(reviews) {
      window.AppUI.openBusinessModal(business, {
        reviews: reviews,
        isSignedIn: !!window.AppAuth.getCurrentUser(),
        isDealClaimed: !!claimedDealIds[businessId],
      });
    }

    window.AppStorage.getReviewsForBusiness(businessId)
      .then(showBusinessWithReviews)
      .catch(function () {
        // If reviews fail to load, still show the business with no reviews.
        showBusinessWithReviews([]);
      });
  }

  /**
   * Toggle a bookmark for the signed-in user.
   * @param {string} businessId The business to bookmark/un-bookmark.
   * @returns {void}
   */
  function handleToggleBookmark(businessId) {
    if (!window.AppAuth.getCurrentUser()) {
      window.AppUI.showToast("Sign in to save favorites.", "error");
      return;
    }
    var wasBookmarked = !!bookmarkedIds[businessId];
    var operation = wasBookmarked
      ? window.AppStorage.removeBookmark(businessId)
      : window.AppStorage.addBookmark(businessId);

    operation
      .then(function () {
        if (wasBookmarked) {
          delete bookmarkedIds[businessId];
        } else {
          bookmarkedIds[businessId] = true;
        }
        window.AppUI.setCardBookmarkState(businessId, !wasBookmarked);
        updateFavoritesCount();
        window.AppUI.showToast(
          wasBookmarked ? "Removed from favorites." : "Saved to favorites."
        );
      })
      .catch(function (error) {
        window.AppUI.showToast(error.message, "error");
      });
  }

  /**
   * Claim a business's deal for the signed-in user, then reveal the code.
   * @param {Object} business The business whose deal is being claimed.
   * @returns {void}
   */
  function handleClaimDeal(business) {
    if (!window.AppAuth.getCurrentUser()) {
      window.AppUI.showToast("Sign in to claim deals.", "error");
      return;
    }
    window.AppStorage.claimDeal(business.id, business.deal.code)
      .then(function () {
        claimedDealIds[business.id] = true;
        window.AppUI.revealDealCode();
        window.AppUI.showToast("Deal claimed! Show the code in-store.");
      })
      .catch(function (error) {
        window.AppUI.showToast(error.message, "error");
      });
  }

  /**
   * Submit a new review, then refresh the modal reviews and grid ratings.
   * @param {Object} business The business being reviewed.
   * @param {number} rating Star rating from 1 to 5.
   * @param {string} text The review text.
   * @returns {void}
   */
  function handleSubmitReview(business, rating, text) {
    if (!window.AppAuth.getCurrentUser()) {
      window.AppUI.showToast("Sign in to leave a review.", "error");
      return;
    }
    window.AppStorage.addReview(business.id, rating, text)
      .then(function () {
        return window.AppStorage.getReviewsForBusiness(business.id);
      })
      .then(function (reviews) {
        window.AppUI.renderModalReviews(reviews);
        return refreshReviewStats();
      })
      .then(function () {
        refreshResults();
        window.AppUI.showToast("Review posted. Thanks!");
      })
      .catch(function (error) {
        window.AppUI.showToast(error.message, "error");
      });
  }

  /**
   * Start the Google sign-in flow.
   * @returns {void}
   */
  function handleSignIn() {
    if (!window.AppFirebase.isConfigured) {
      window.AppUI.showToast("Firebase is not connected yet. See setup steps.", "error");
      return;
    }
    window.AppAuth.signInWithGoogle().catch(function (error) {
      window.AppUI.showToast(error.message || "Sign-in failed.", "error");
    });
  }

  /**
   * Sign the current user out.
   * @returns {void}
   */
  function handleSignOut() {
    window.AppAuth.signOutUser();
  }

  /**
   * Open the favorites modal.
   * @returns {void}
   */
  function handleOpenFavorites() {
    window.AppUI.openFavoritesModal(getFavoriteBusinesses());
  }

  /**
   * Remove a favorite from the favorites modal.
   * @param {string} businessId The business to remove.
   * @returns {void}
   */
  function handleRemoveFavorite(businessId) {
    if (!window.AppAuth.getCurrentUser()) {
      window.AppUI.showToast("Sign in to manage favorites.", "error");
      return;
    }
    window.AppStorage.removeBookmark(businessId)
      .then(function () {
        delete bookmarkedIds[businessId];
        updateFavoritesCount();
        window.AppUI.setCardBookmarkState(businessId, false);
        window.AppUI.openFavoritesModal(getFavoriteBusinesses());
        refreshResults();
      })
      .catch(function (error) {
        window.AppUI.showToast(error.message, "error");
      });
  }

  /**
   * Export the favorites list as a downloadable HTML report.
   * @returns {void}
   */
  function handleExportFavorites() {
    var favorites = getFavoriteBusinesses();
    if (favorites.length === 0) {
      window.AppUI.showToast("Add some favorites first.", "error");
      return;
    }
    var html = buildFavoritesReportHtml(favorites);
    var blob = new Blob([html], { type: "text/html" });
    var url = URL.createObjectURL(blob);
    var link = document.createElement("a");
    link.href = url;
    link.download = "my-favorite-businesses.html";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    window.AppUI.showToast("Favorites exported.");
  }

  /**
   * Print the favorites list using the browser's print dialog.
   * @returns {void}
   */
  function handlePrintFavorites() {
    var favorites = getFavoriteBusinesses();
    if (favorites.length === 0) {
      window.AppUI.showToast("Add some favorites first.", "error");
      return;
    }
    var printWindow = window.open("", "_blank");
    if (!printWindow) {
      window.AppUI.showToast("Allow pop-ups to print.", "error");
      return;
    }
    printWindow.document.write(buildFavoritesReportHtml(favorites));
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }

  /**
   * React to auth state changes: update the header and reload user data.
   * @param {Object|null} user The signed-in user, or null.
   * @returns {void}
   */
  function handleAuthChange(user) {
    window.AppUI.updateAuthState(user);
    Promise.all([
      window.AppStorage.getBookmarkIds(),
      window.AppStorage.getClaimedDealIds(),
    ]).then(function (results) {
      var bookmarkIdList = results[0];
      var claimedDealIdList = results[1];
      bookmarkedIds = {};
      bookmarkIdList.forEach(function (id) {
        bookmarkedIds[id] = true;
      });
      claimedDealIds = {};
      claimedDealIdList.forEach(function (id) {
        claimedDealIds[id] = true;
      });
      updateFavoritesCount();
      refreshResults();
    });
  }

  /**
   * Initialize the application: wire UI handlers, load data, and start auth.
   * @returns {void}
   */
  function startApp() {
    window.AppUI.init({
      onQueryChange: handleQueryChange,
      onOpenBusiness: handleOpenBusiness,
      onToggleBookmark: handleToggleBookmark,
      onClaimDeal: handleClaimDeal,
      onSubmitReview: handleSubmitReview,
      onSignIn: handleSignIn,
      onSignOut: handleSignOut,
      onOpenFavorites: handleOpenFavorites,
      onRemoveFavorite: handleRemoveFavorite,
      onExportFavorites: handleExportFavorites,
      onPrintFavorites: handlePrintFavorites,
    });

    window.AppData.loadBusinesses()
      .then(function () {
        window.AppUI.populateCategories(window.AppData.getCategories());
        return refreshReviewStats();
      })
      .then(function () {
        refreshResults();
        // Start listening for auth changes once the catalog is ready.
        window.AppAuth.onAuthChange(handleAuthChange);
      })
      .catch(function () {
        window.AppUI.showToast(
          "Could not load businesses. If opened from a file, run via the hosted URL.",
          "error"
        );
      });
  }

  // Scripts load at the end of <body>, but guard against early execution anyway.
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", startApp);
  } else {
    startApp();
  }
})();
